version: "3.9"

services:
  nginx:
    init: true
    build:
      context: .
    environment:
      NGINX_HOST: 127.0.0.1
      NGINX_PORT: 80
      FASTCGI_HOST: fpm
      FASTCGI_PORT: 9000
    ports: 
      - 8089:80
    volumes:
      - ./html:/var/www/html
      - ./nginx/templates:/etc/nginx/templates

    entrypoint: [
      "wait-for-it", "fpm:9000", "--", 
      "/docker-entrypoint.sh",
      "nginx", "-g", "daemon off;"
    ]

  fpm:
    image: php:8.0-fpm
    volumes:
      - ./html:/var/www/html
